spring:
  mail:
      host: smtp.163.com
      # 你申请的163邮箱
      username: zobf45c4qfe_kgokix@163.com
      # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
      password: PQPLXMGYSKMHNRTB
#  rabbitmq:
#    addresses: localhost
#    username: admin
#    password: admin
#    virtual-host: /
  application:
    name:
      my-project-backend
  security:
    filter:
      order: -100
    jwt:
      key: nhxtbymmjsnzhu
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/bolg_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
